"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-w6afz*g)wmo_f*_%-e70u2#s5*utikdec3vx)24y&^3^7-+*1m"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
CELERY_TASK_ALWAYS_EAGER = True
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
ALLOWED_HOSTS = ["*"]
UNFOLD_STUDIO_ALWAYS_OPEN = True


# Application definition

INSTALLED_APPS = [
    "service.apps.ServiceConfig",
    "django_celery_beat",
    "django_extensions",
    "sslserver",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_yasg",
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "import_export",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "server.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


UNFOLD = {
    "ENVIRONMENT": (
        ["Debug Server", "danger"] if DEBUG else ["Production Server", "success"]
    ),
    "SITE_URL": "https://example.com",
    "SITE_TITLE": "Techrar - Your One-Stop Online Store",
    "SITE_HEADER": "Admin Panel",
    "SITE_SUBHEADER": "Manage products, orders, and customers",
    "SITE_DROPDOWN": [
        {
            "icon": "storefront",
            "title": _("View Site"),
            "link": "https://example.com",
        },
        {
            "icon": "diamond",
            "title": _("Dashboad"),
            "link": reverse_lazy("admin:index"),
        },
    ],
    "SHOW_LANGUAGES": False,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("⚙️ General"),
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("📢 Marketing & Branding"),
                "collapsible": False,
                "items": [
                  
                    {
                        "title": _("Merchants"),
                        "icon": "store",
                        "link": reverse_lazy("admin:service_merchant_changelist"),
                    },
                       {
                        "title": _("Recipient"),
                        "icon": "draw_abstract",
                        "link": reverse_lazy("admin:service_recipient_changelist"),
                    },
                    {
                        "title": _("Template"),
                        "icon": "category",
                        "link": reverse_lazy("admin:service_template_changelist"),
                    },
                    {
                        "title": _("Campaigns"),
                        "icon": "campaign",
                        "link": reverse_lazy("admin:service_campaign_changelist"),
                    },
                    {
                        "title": _("Campaign Status"),
                        "icon": "monitoring",
                        "link": "/admin/django_celery_beat/periodictask/",
                    },
                 
                ],
            },
        ],
    },
}
