# Generated by Django 5.2.1 on 2025-05-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchant",
            options={},
        ),
        migrations.AlterModelManagers(
            name="merchant",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="email",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="username",
        ),
    ]
