# Generated by Django 5.2.1 on 2025-05-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_alter_merchant_options_alter_merchant_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="user_permissions",
        ),
    ]
