# Generated by Django 5.2.1 on 2025-05-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_remove_merchant_user_permissions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Merchant",
        ),
    ]
