# Generated by Django 5.2.1 on 2025-05-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "device_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active_user", models.BooleanField(default=True)),
                (
                    "custom_tags",
                    models.JSONField(
                        blank=True,
                        help_text="Optional tag-based segmentation",
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
