# Generated by Django 5.2.1 on 2025-05-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_recipient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        help_text="A/B test variant label (e.g., A, B)",
                        max_length=1,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="templates",
            field=models.ManyToManyField(
                related_name="campaigns", to="service.template"
            ),
        ),
    ]
