# Generated by Django 5.2.1 on 2025-05-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_template_campaign_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="recipients",
            field=models.ManyToManyField(to="service.recipient"),
        ),
    ]
