# Generated by Django 5.2.1 on 2025-05-31 22:51

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("service", "0008_campaign_recipients"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[],
            options={
                "verbose_name": "Merchant",
                "verbose_name_plural": "Merchants",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
