# Generated by Django 5.2.1 on 2025-06-01 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0009_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="merchant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="service.merchant",
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="merchant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="service.merchant",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="merchant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="service.merchant",
            ),
        ),
    ]
